### ISSUE TITLE
Generate builder properties with TODO function

### ISSUE THREAD

**Issue by drewhamilton** [Hariofspades/dsl-api-generator#2]
Currently the builder properties are generated like this:
```kt
@set:JvmSynthetic
lateinit var example: String //TODO: change to var and set default value
```

Since defaults are almost always desired, making use of Kotlin's TODO function would help here IMO. Then the property doesn't have to be `lateinit`, and runtime fails if the TODO isn't replaced.

```kt
@set:JvmSynthetic
var example: String = TODO("Provide a default value")
```

**Comment by Hariofspades** [comment]
Wonderful. Let's do this
