### ISSUE TITLE
Use factory function naming convention for top-level DSL function

### ISSUE THREAD

**Issue by drewhamilton** [Hariofspades/dsl-api-generator#3]
If I generate a `SomeClass` class, I want the DSL factory function to also be named `SomeClass`, rather than `someClass`, per the Kotlin style guide's [factory function naming convention](https://kotlinlang.org/docs/reference/coding-conventions.html#function-names). Either making this the plugin's behavior, or adding an option to do this, would be nice IMO.

**Comment by Hariofspades** [comment]
Proposed solution:

- To provide a checkbox, checked by default "Use PascalCase for generated DSL function" + DSL function should be JvmSynthetic by default
